language: node_js
node_js:
  - node
branches:
  only: gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ${TRAVIS_BUILD_DIR}/dist
  target_branch: master
  on:
    branch: gh-pages
